### PR TITLE
Reorder package.json and add fields

### LINKED ISSUE #17: Test folder is exposed on NPM
Hey there,
The `test` folder is downloaded on every NPM installation. Can you exclude it and push a new release?

### PR DESCRIPTION
**Pull request by dada1134**
Fields added:
- homepage
- bugs
- files

The `files` field fixes #17

### CODE REVIEW

**Comment by Jameskmonger** [comment]
@substack Could this be merged?

**Comment by hisuwh** [comment]
@substack Would be useful if this was merged

**Comment by OwenPattison** [comment]
@substack merge it

**Comment by Jameskmonger** [comment]
Hey @substack any change this can be merged?

**Pull request closed without merging**
